# CMake generated Testfile for 
# Source directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vnl/tests
# Build directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vnl/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vnl_test_matlab "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_with_core_utils" "test_matlab")
add_test(vnl_test_sample "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_with_core_utils" "test_sample")
add_test(vnl_basic_operation_timings "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_basic_operation_timings")
add_test(vnl_test_bignum "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_bignum")
add_test(vnl_test_decnum "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_decnum")
add_test(vnl_test_complex "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_complex")
add_test(vnl_test_complexify "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_complexify")
add_test(vnl_test_diag_matrix "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_diag_matrix")
add_test(vnl_test_diag_matrix_fixed "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_diag_matrix_fixed")
add_test(vnl_test_file_matrix "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_file_matrix")
add_test(vnl_test_finite "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_finite")
add_test(vnl_test_inverse "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_inverse")
add_test(vnl_test_math "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_math")
add_test(vnl_test_matrix "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_matrix")
add_test(vnl_test_container_interface "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_container_interface")
add_test(vnl_test_matrix_exp "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_matrix_exp")
add_test(vnl_test_matrix_fixed "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_matrix_fixed")
add_test(vnl_test_vector_fixed_ref "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_vector_fixed_ref")
add_test(vnl_test_matrix_fixed_ref "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_matrix_fixed_ref")
add_test(vnl_test_numeric_traits "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_numeric_traits")
add_test(vnl_test_na "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_na")
add_test(vnl_test_random "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_random")
add_test(vnl_test_rational "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_rational")
add_test(vnl_test_polynomial "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_polynomial")
add_test(vnl_test_real_polynomial "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_real_polynomial")
add_test(vnl_test_real_npolynomial "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_real_npolynomial")
add_test(vnl_test_resize "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_resize")
add_test(vnl_test_rotation_matrix "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_rotation_matrix")
add_test(vnl_test_sym_matrix "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_sym_matrix")
add_test(vnl_test_transpose "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_transpose")
add_test(vnl_test_fastops "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_fastops")
add_test(vnl_test_vector "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_vector")
add_test(vnl_test_gamma "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_gamma")
add_test(vnl_test_arithmetic "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_arithmetic")
add_test(vnl_test_alignment "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_alignment")
add_test(vnl_test_hungarian_algorithm "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_hungarian_algorithm")
add_test(vnl_test_integrant "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_integrant")
add_test(vnl_test_bessel "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_bessel")
add_test(vnl_test_quaternion "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_quaternion")
add_test(vnl_test_crs_index "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_crs_index")
add_test(vnl_test_sparse_lst_sqr_function "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_sparse_lst_sqr_function")
add_test(vnl_test_power "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_power")
add_test(vnl_test_sparse_matrix "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_sparse_matrix")
add_test(test_pow_log "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_pow_log")
add_test(test_vnl_index_sort "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_test_all" "test_vnl_index_sort")
