# CMake generated Testfile for 
# Source directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/algo/tests
# Build directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/algo/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vil_algo_test_gauss_filter "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_gauss_filter")
add_test(vil_algo_test_gauss_reduce "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_gauss_reduce")
add_test(vil_algo_test_colour_space "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_colour_space")
add_test(vil_algo_test_convolve_1d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_convolve_1d")
add_test(vil_algo_test_convolve_2d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_convolve_2d")
add_test(vil_algo_test_correlate_1d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_correlate_1d")
add_test(vil_algo_test_correlate_2d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_correlate_2d")
add_test(vil_algo_test_exp_filter_1d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_exp_filter_1d")
add_test(vil_algo_test_exp_grad_filter_1d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_exp_grad_filter_1d")
add_test(vil_algo_test_line_filter "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_line_filter")
add_test(vil_algo_test_threshold "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_threshold")
add_test(vil_algo_test_grid_merge "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_grid_merge")
add_test(vil_algo_test_find_4con_boundary "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_find_4con_boundary")
add_test(vil_algo_test_fft "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_fft")
add_test(vil_algo_test_histogram "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_histogram")
add_test(vil_algo_test_histogram_equalise "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_histogram_equalise")
add_test(vil_algo_test_distance_transform "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_distance_transform")
add_test(vil_algo_test_blob "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_blob")
add_test(vil_algo_test_find_peaks "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_find_peaks")
add_test(vil_algo_test_find_plateaus "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_find_plateaus")
add_test(vil_algo_test_region_finder "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_region_finder")
add_test(vil_algo_test_corners "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_corners")
add_test(vil_algo_test_cartesian_differential_invariants "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_cartesian_differential_invariants")
add_test(vil_algo_test_binary_erode "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_binary_erode")
add_test(vil_algo_test_binary_dilate "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_binary_dilate")
add_test(vil_algo_test_greyscale_dilate "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_greyscale_dilate")
add_test(vil_algo_test_greyscale_erode "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_greyscale_erode")
add_test(vil_algo_test_median "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_median")
add_test(vil_algo_test_suppress_non_max "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_suppress_non_max")
add_test(vil_algo_test_suppress_non_plateau "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_suppress_non_plateau")
add_test(vil_algo_test_algo_sobel "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_sobel")
add_test(vil_algo_test_abs_shuffle_distance "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_abs_shuffle_distance")
add_test(vil_algo_test_suppress_non_max_edges "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_suppress_non_max_edges")
add_test(vil_algo_test_checker_board "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_checker_board")
add_test(vil_algo_test_quad_distance_function "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_quad_distance_function")
add_test(vil_algo_test_flood_fill "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_algo_test_all" "test_algo_flood_fill")
