# CMake generated Testfile for 
# Source directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests
# Build directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vil_test_image_resource "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_image_resource")
add_test(vil_test_image_view "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_image_view")
add_test(vil_test_memory_chunk "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_memory_chunk")
add_test(vil_test_pixel_format "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_pixel_format")
add_test(vil_test_border "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_border")
add_test(vil_test_round "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_round")
add_test(vil_test_pyramid_image_view "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_pyramid_image_view")
add_test(vil_test_file_format_read "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_file_format_read" "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests/file_read_data")
add_test(vil_test_save_load_image "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_save_load_image")
add_test(vil_test_image_loader_robustness "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_image_loader_robustness")
add_test(vil_test_stream "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_stream" "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests/file_read_data")
add_test(vil_test_4_plane_tiff "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_4_plane_tiff" "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests/file_read_data")
add_test(vil_test_deep_copy_3_plane "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_deep_copy_3_plane")
add_test(vil_test_image_view_maths "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_image_view_maths")
add_test(vil_test_convert "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_convert" "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests/file_read_data")
add_test(vil_test_rotate_image "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_rotate_image")
add_test(vil_test_warp "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_warp")
add_test(vil_test_bilin_interp "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_bilin_interp")
add_test(vil_test_sample_profile_bilin "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_sample_profile_bilin")
add_test(vil_test_sample_grid_bilin "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_sample_grid_bilin")
add_test(vil_test_resample_bilin "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_resample_bilin")
add_test(vil_test_bicub_interp "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_bicub_interp")
add_test(vil_test_sample_profile_bicub "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_sample_profile_bicub")
add_test(vil_test_sample_grid_bicub "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_sample_grid_bicub")
add_test(vil_test_resample_bicub "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_resample_bicub")
add_test(vil_test_nearest_interp "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_nearest_interp")
add_test(vil_test_resample_nearest "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_resample_nearest")
add_test(vil_test_math_value_range "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_math_value_range")
add_test(vil_test_math_median "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_math_median")
add_test(vil_test_na "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_na")
add_test(vil_test_blocked_image_resource "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_blocked_image_resource" "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests/file_read_data")
add_test(vil_test_image_list "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_image_list")
add_test(vil_test_pyramid_image_resource "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vil_test_all" "test_pyramid_image_resource" "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vil/tests/file_read_data")
