# CMake generated Testfile for 
# Source directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vnl/algo/tests
# Build directory: /media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/core/vnl/algo/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vnl_algo_test_algo "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_algo")
add_test(vnl_algo_test_amoeba "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_amoeba")
add_test(vnl_algo_test_cholesky "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_cholesky")
add_test(vnl_algo_test_complex_algo "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_complex_algo")
add_test(vnl_algo_test_complex_eigensystem "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_complex_eigensystem")
add_test(vnl_algo_test_convolve "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_convolve")
add_test(vnl_algo_test_cpoly_roots "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_cpoly_roots")
add_test(vnl_algo_test_determinant "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_determinant")
add_test(vnl_algo_test_fft "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_fft")
add_test(vnl_algo_test_fft1d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_fft1d")
add_test(vnl_algo_test_fft2d "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_fft2d")
add_test(vnl_algo_test_functions "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_functions")
add_test(vnl_algo_test_generalized_eigensystem "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_generalized_eigensystem")
add_test(vnl_algo_test_ldl_cholesky "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_ldl_cholesky")
add_test(vnl_algo_test_levenberg_marquardt "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_levenberg_marquardt")
add_test(vnl_algo_test_matrix_update "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_matrix_update")
add_test(vnl_algo_test_minimizers "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_minimizers")
add_test(vnl_algo_test_powell "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_powell")
add_test(vnl_algo_test_qr "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_qr")
add_test(vnl_algo_test_qsvd "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_qsvd")
add_test(vnl_algo_test_rank "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_rank")
add_test(vnl_algo_test_real_eigensystem "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_real_eigensystem")
add_test(vnl_algo_test_rnpoly_roots "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_rnpoly_roots")
add_test(vnl_algo_test_rpoly_roots "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_rpoly_roots")
add_test(vnl_algo_test_integral "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_integral")
add_test(vnl_algo_test_solve_qp "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_solve_qp")
add_test(vnl_algo_test_sparse_lu "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_sparse_lu")
add_test(vnl_algo_test_bracket_minimum "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_bracket_minimum")
add_test(vnl_algo_test_brent_minimizer "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_brent_minimizer")
add_test(vnl_algo_test_sparse_lm "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_sparse_lm")
add_test(vnl_algo_test_sparse_matrix "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_sparse_matrix")
add_test(vnl_algo_test_svd "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_svd")
add_test(vnl_algo_test_svd_fixed "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_svd_fixed")
add_test(vnl_algo_test_symmetric_eigensystem "/media/agent/data2/zhangeaky/gmmreg/Cpp/vxl-2.0.2/bin/vnl_algo_test_all" "test_symmetric_eigensystem")
